//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckListToolWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\\\Commit_CheckList")]
        public string CheckListPath {
            get {
                return ((string)(this["CheckListPath"]));
            }
            set {
                this["CheckListPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\Commit_CheckList\\CheckListGroups")]
        public string CheckListGroupPath {
            get {
                return ((string)(this["CheckListGroupPath"]));
            }
            set {
                this["CheckListGroupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\Commit_CheckList\\Developres.xml")]
        public string UsersCommitsPath {
            get {
                return ((string)(this["UsersCommitsPath"]));
            }
            set {
                this["UsersCommitsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\ImpactAnalysis\\ImpactAnalysis.xlsx")]
        public string ImpactAnalysisExcelPath {
            get {
                return ((string)(this["ImpactAnalysisExcelPath"]));
            }
            set {
                this["ImpactAnalysisExcelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\Commit_CheckList\\check.png")]
        public string IconPath {
            get {
                return ((string)(this["IconPath"]));
            }
            set {
                this["IconPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\Commit_CheckList\\left_Arrow.png")]
        public string Left_Arrow {
            get {
                return ((string)(this["Left_Arrow"]));
            }
            set {
                this["Left_Arrow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R:\\CT Apps\\Tools\\Commit_CheckList\\Right_Arrow.png")]
        public string Right_Arrow {
            get {
                return ((string)(this["Right_Arrow"]));
            }
            set {
                this["Right_Arrow"] = value;
            }
        }
    }
}
